[package]
name = "tsp-sim-gui"
version = "0.1.0"
authors = ["Ernesto Menéndez <pyalec@gmail.com>"]
edition = "2021"

[dependencies]
tsp-sim-agent = { path = "../tsp-sim-agent" }

anyhow = { version = "1.0", features = ["backtrace"] }

eframe = "0.19"
ron = "0.8"
itertools = "0.10"
